[tools]
deno = { version = "2.5.6" }
dotnet = { version = "10.0.100" }
go = { version = "1.25.4" }
gradle = { version = "9.2.1" }
java = { version = "25.0.1" }
python = { version = "3.13.2" }
ruby = { version = "3.4.7" }
rust = { version = "1.91" }
uv = { version = "0.9.11" }
