[package]
name = "aoc-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
hex = "0.4.3"
itertools = "0.14.0"
lazy_static = "1.5.0"
md-5 = "0.10.6"
regex = "1.12.2"
